#!/bin/sh -eu

cd "$(dirname "$0")"

nix run \
    --ignore-environment \
    --file nix \
    shajra-keyboards-flash-scripts.ergodoxez \
    --command \
    flash-run \
    --nix "$(command -v nix)" \
    "$@"
