#!/bin/sh -eu

cd "$(dirname "$0")/.."

# DESIGN: keep Nix commands on path. When calling Nix commands, it's better to
# use the versions already on that path, rather than pull in pinned version.
# This is the only exception. Everything else is pinned.
NIX_BIN_LINK="$(command -v nix)"
NIX_BIN_ORIG="$(
    nix run '((import (import ./nix/sources.nix).nixpkgs {}).coreutils)' \
        --command readlink -f "$NIX_BIN_LINK")"
PATH="$(dirname "$NIX_BIN_ORIG")"
export PATH

nix run \
    --ignore-environment \
    --keep PATH \
    --file ./default.nix \
    '(
        let sources = import ./nix/sources.nix;
            overlay = _: self: {
                org2gfm = import ../org2gfm {};
                #org2gfm = import sources.org2gfm {};
            };
            pkgs = import sources.nixpkgs {
                config = {};
                overlays = [ overlay ];
            };
        in with pkgs; [ coreutils gnugrep org2gfm ]
    )' \
    --command org2gfm --evaluate "$@"
